--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 15/11/2019 11:16:15 a. m.
-- Server version: 5.6.37
-- Client version: 4.1
-- Please backup your database before running this script
--


SET NAMES 'utf8';

--
-- Set default database
--
USE TerrazaBar;

--
-- Create table `tb_inventario`
--
CREATE TABLE tb_inventario (
  id INT(11) NOT NULL AUTO_INCREMENT,
  IdTipoItem INT(11) NOT NULL,
  IdItem INT(11) NOT NULL,
  IdUnidad INT(11) NOT NULL,
  Min FLOAT DEFAULT NULL,
  Max FLOAT DEFAULT NULL,
  TipoMovimiento TINYINT(4) DEFAULT NULL,
  Movimiento FLOAT DEFAULT 0,
  Existencia FLOAT DEFAULT NULL,
  UltimoIngreso DATETIME DEFAULT NULL,
  IdUltimoIngreso INT DEFAULT NULL,
  UltimaSalida DATETIME DEFAULT NULL,
  IdUltimaSalida INT DEFAULT NULL,
  RegistroManual BOOL DEFAULT 0,
  Comentarios VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB;

ALTER TABLE TerrazaBar.tb_inventario 
  ADD UNIQUE INDEX UK_tb_inventario(IdTipoItem, IdItem);