--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 08/11/2019 07:59:49 p. m.
-- Server version: 5.6.37
-- Client version: 4.1
-- Please backup your database before running this script
--


SET NAMES 'utf8';

--
-- Set default database
--
USE TerrazaBar;

--
-- Create column `Item` on table `tb_compras_detalle`
--
ALTER TABLE tb_compras_detalle 
  ADD COLUMN Item VARCHAR(255) DEFAULT NULL AFTER IdItem;
  ADD COLUMN Unidad VARCHAR(255) DEFAULT NULL AFTER IdUnidad,
  ADD COLUMN IdUnidadSalida INT(11) DEFAULT NULL AFTER Cantidad,
  ADD COLUMN UnidadSalida VARCHAR(255) DEFAULT NULL AFTER IdUnidadSalida;
  ADD COLUMN FactorConversion decimal(10,2) DEFAULT NULL AFTER  Cantidad

ALTER TABLE tb_compras_detalle 
  DROP COLUMN IdUnidadOriginal;
